[versions]
org-springframework-boot = "3.4.3"
dependency-management = "1.1.7"
swagger-annotations-version = "2.2.22"


[libraries]

spring-boot-starter-web = {group = "org.springframework.boot", name = "spring-boot-starter-web"}
lombok = {group = "org.projectlombok", name = "lombok"}
swagger-annotations = {group = "io.swagger.core.v3", name = "swagger-annotations", version.ref = "swagger-annotations-version"}

[plugins]
org-springframework-boot = {id = "org.springframework.boot", version.ref = "org-springframework-boot"}
dependency-management = {id = "io.spring.dependency-management", version.ref = "dependency-management"}